[package]
name = "__SOLUTION_NAME__"
version = "0.1.0"
edition = "2024"

[lib]
name = "__SOLUTION_NAME__"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[dependencies]
wasm-bindgen = "0.2.100"
aoc_utils = { path = "../../../aoc_utils" }
