[package]
name = "solution_2023_12_2"
version = "0.1.0"
edition = "2024"

[lib]
name = "solution_2023_12_2"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[dependencies]
wasm-bindgen = "0.2.100"
memoize = "0.5.1"
