[package]
name = "solution_2024_10_1"
version = "0.1.0"
edition = "2024"

[lib]
name = "solution_2024_10_1"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib"]

[dependencies]
wasm-bindgen = "0.2.100"
